<a href="https://colab.research.google.com/github/InowaR/network/blob/main/network1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np
# --------------------------------------------------------------------
input = np.array([1,2])
output_one = np.array([1,2])
output_second = np.array([1,2])
delta = np.array([9,23]) # <-------------- [100 - 91], [123 - 100]
# -------------------------------------------------------------------- 
def layer():
  a = input # <-------------------------------------inputs
  b = output_one # <--------------------------------outputs
  w = np.array([len(a) * len(b)])
  w = np.arange(1, w+1) 
  w = np.array([1,2,3,4]) # <-----------------------weights
  w = w.reshape(len(b),len(a))
  temp = np.tile(a,len(b))
  temp = np.split(temp, len(b))
  temp = np.vstack(temp)
  frame_a = pd.DataFrame(temp.T)
  frame_b = pd.DataFrame(b)
  frame_w = pd.DataFrame(w.T) 
  a_mul = frame_a * frame_w
  final = a_mul.sum(axis ='index')
  return final
def layer_second():
  a = layer()
  a = a.to_numpy()
  b = output_one # <--------------------------------outputs
  w = np.array([len(a) * len(b)])
  w = np.arange(1, w+1)
  w = np.array([5,6,7,8]) # <-----------------------weights
  w = w.reshape(len(b),len(a))
  temp = np.tile(a,len(b))
  temp = np.split(temp, len(b))
  temp = np.vstack(temp)
  frame_a = pd.DataFrame(temp.T)
  frame_b = pd.DataFrame(b)
  frame_w = pd.DataFrame(w.T) 
  a_mul = frame_a * frame_w
  final_second = a_mul.sum(axis ='index')
  return final_second
layer_second()

0     91
1    123
dtype: int64

In [37]:
def update():
  a = input
  b = output_one
  c = output_second
  w = np.array([5,6,7,8])
  b_tile = np.tile(b, 2)
  b_repeat = np.repeat(b,2)
  c_repeat = np.repeat(c, 2)
  a_tile = np.tile(a,2)
  b_new = np.ones(len(b))
  b_new = b_new - b
  b_new = np.repeat(b_new, 2)
  errors = delta # <-------------------------- delta (target-c)
  errors = np.repeat(errors, 2)
  errors = pd.DataFrame(errors)
  c_errors = pd.DataFrame(c_repeat)
  ones = np.ones(len(w))
  ones = pd.DataFrame(ones)
  c_one = errors * c_errors * ones - errors * c_errors * c_errors
  c_new = np.split(c_repeat, 2)
  c_weights = w * c_repeat
  c_weights = np.split(c_weights, 2)
  c_weights = pd.DataFrame(c_weights)
  c_weights = c_weights.sum(axis=1)
  c_weights.to_numpy()
  c_weights = np.repeat(c_weights, 2)
  c_w = c_weights.to_numpy()
  c_w = pd.DataFrame(c_w)
  c_frame = c_one * c_w
  b_tile = pd.DataFrame(b_tile)
  c_repeat = pd.DataFrame(c_repeat)
  mul = c_repeat * b_tile
  a_tile = pd.DataFrame(a_tile)
  b_repeat = pd.DataFrame(b_repeat)
  b_new = pd.DataFrame(b_new)
  b_mul = b_repeat * b_new
  mul_second = a_tile * b_mul * c_frame
  return mul_second
update()

        0
0     0.0
1     0.0
2  2760.0
3  5520.0

In [38]:
def update_second():
  a = input
  b = output_one
  c = output_second
  w = np.array([5,6,7,8])
  b_tile = np.tile(b, 2)
  b_repeat = np.repeat(b,2)
  c_repeat = np.repeat(c, 2)
  a_tile = np.tile(a,2)
  b_new = np.ones(len(b))
  b_new = b_new - b
  b_new = np.repeat(b_new, 2)
  errors = delta # <-------------------------- delta (target-c)
  errors = np.repeat(errors, 2)
  errors = pd.DataFrame(errors)
  c_errors = pd.DataFrame(c_repeat)
  ones = np.ones(len(w))
  ones = pd.DataFrame(ones)
  c_one = errors * c_errors * ones - errors * c_errors * c_errors
  c_new = np.split(c_repeat, 2)
  c_weights = w * c_repeat
  c_weights = np.split(c_weights, 2)
  c_weights = pd.DataFrame(c_weights)
  c_weights = c_weights.sum(axis=1)
  c_weights.to_numpy()
  c_weights = np.repeat(c_weights, 2)
  c_w = c_weights.to_numpy()
  c_w = pd.DataFrame(c_w)
  c_frame = c_one * c_w
  b_tile = pd.DataFrame(b_tile)
  c_repeat = pd.DataFrame(c_repeat)
  mul = c_repeat * b_tile
  a_tile = pd.DataFrame(a_tile)
  b_repeat = pd.DataFrame(b_repeat)
  b_new = pd.DataFrame(b_new)
  b_mul = b_repeat * b_new
  mul_second = a_tile * b_mul * c_frame
  return mul
update_second()

   0
0  1
1  2
2  2
3  4

In [39]:
def layer_update():
  update()
  a = input # <-------------------------------------inputs
  b = output_one # <--------------------------------outputs
  weights = update()
  weights = weights.to_numpy()
  w = np.array(weights) # <-------------------------weights
  w = w.reshape(len(b),len(a))
  temp = np.tile(a,len(b))
  temp = np.split(temp, len(b))
  temp = np.vstack(temp)
  frame_a = pd.DataFrame(temp.T)
  frame_b = pd.DataFrame(b)
  frame_w = pd.DataFrame(w.T) 
  a_mul = frame_a * frame_w
  final = a_mul.sum(axis ='index')
  return final
layer_update()
def layer_second_update():
  a = layer_update()
  a = a.to_numpy()
  b = output_one # <------------------------------------outputs
  weights = update_second()
  weights = weights.to_numpy()
  w = np.array(weights) # <-----------------------------weights
  w = w.reshape(len(b),len(a))
  temp = np.tile(a,len(b))
  temp = np.split(temp, len(b))
  temp = np.vstack(temp)
  frame_a = pd.DataFrame(temp.T)
  frame_b = pd.DataFrame(b)
  frame_w = pd.DataFrame(w.T) 
  a_mul = frame_a * frame_w
  final_second = a_mul.sum(axis ='index')
  return final_second
layer_second_update()

0    27600.0
1    55200.0
dtype: float64